// Copyright (c) 1998, 2021, Oracle and/or its affiliates. All rights reserved.

// Applet Selection APDU Script
//
// Package:     Wallet.com.oracle.jcclassic.samples.wallet
// Package AID: //aid/A000000062/03010C06
// Applet:      com.oracle.jcclassic.samples.wallet.StudentCard
// Applet AID:  //aid/A000000062/03010C0601
//

// Select com.oracle.jcclassic.samples.wallet.StudentCard applet
0x00 0xA4 0x04 0x00 0x0A 0xA0 0x00 0x00 0x00 0x62 0x03 0x01 0x0C 0x06 0x01 0x7F;
